---
- name: Configure Schedemy Spring Boot AMI
  hosts: all
  become: yes
  tasks:
    - name: Install Java 17
      apt:
        name: openjdk-17-jre-headless
        state: present
        update_cache: yes

    - name: Ensure app directory exists
      file:
        path: /home/ec2-user/HTU-Schedemy-Website-Backend
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy JAR file
      copy:
        # This assumes your GitHub Action just ran 'mvn package'
        src: target/EduSched-0.0.1-SNAPSHOT.jar 
        dest: /home/ec2-user/HTU-Schedemy-Website-Backend/target/EduSched-0.0.1-SNAPSHOT.jar
        owner: ec2-user
        mode: '0755'

    - name: Create Systemd Service
      copy:
        dest: /etc/systemd/system/final.service
        content: |
          [Unit]
          Description=Schedemy Spring Boot Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/HTU-Schedemy-Website-Backend
          ExecStart=/usr/bin/java -jar /home/ec2-user/HTU-Schedemy-Website-Backend/target/EduSched-0.0.1-SNAPSHOT.jar
          SuccessExitStatus=143
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Enable the service
      systemd:
        name: final
        enabled: yes
