---
- name: Configure Spring Boot AMI
  hosts: all
  become: yes
  tasks:
    - name: Install Java 17
      apt:
        name: openjdk-17-jre-headless
        state: present
        update_cache: yes

    - name: Create App Directory
      file:
        path: /opt/myapp
        state: directory
        owner: ubuntu

    - name: Copy Spring Boot JAR
      copy:
        src: target/my-app-0.0.1-SNAPSHOT.jar # Ensure this matches your pom.xml name
        dest: /opt/myapp/app.jar
        mode: '0755'

    - name: Create Systemd Service
      copy:
        dest: /etc/systemd/system/myapp.service
        content: |
          [Unit]
          Description=Spring Boot Application
          After=network.target

          [Service]
          User=ubuntu
          # Optimize JVM memory for t3.micro/small
          ExecStart=/usr/bin/java -Xmx512m -Xms512m -jar /opt/myapp/app.jar
          SuccessExitStatus=143
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Enable and Start Service
      systemd:
        name: myapp
        enabled: yes
        state: started
