---
- name: Configure Schedemy Spring Boot AMI
  hosts: all
  become: yes
  tasks:
    - name: Wait for apt lock
      shell: "while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 5; done"
      changed_when: false

    - name: Fix Broken Packages
      shell: "apt-get clean && apt-get update --fix-missing && apt-get install -f -y"

    - name: Install Java 17
      apt: { name: openjdk-17-jre-headless, state: present, update_cache: yes }

    - name: Ensure app directory exists
      file: { path: /home/ubuntu/HTU-Schedemy-Website-Backend/target, state: directory, owner: ubuntu, recurse: yes }

    - name: Copy JAR
      copy: { src: target/EduSched-0.0.1-SNAPSHOT.jar, dest: /home/ubuntu/HTU-Schedemy-Website-Backend/target/EduSched-0.0.1-SNAPSHOT.jar, mode: '0755' }

    - name: Create Systemd Service
      copy:
        dest: /etc/systemd/system/final.service
        content: |
          [Unit]
          Description=Schedemy Spring Boot Application
          After=network.target
          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/HTU-Schedemy-Website-Backend
          ExecStart=/usr/bin/java -jar /home/ubuntu/HTU-Schedemy-Website-Backend/target/EduSched-0.0.1-SNAPSHOT.jar
          SuccessExitStatus=143
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Enable final.service
      systemd: { name: final, enabled: yes }
