---
- name: Configure Schedemy Spring Boot AMI
  hosts: all
  become: yes
  tasks:
    - name: Install Java 17
      dnf: # Amazon Linux uses dnf
        name: java-17-amazon-corretto-devel
        state: present

    - name: Ensure app directory exists
      file:
        path: /home/ec2-user/HTU-Schedemy-Website-Backend/target
        state: directory
        owner: ec2-user
        group: ec2-user
        recurse: yes

    - name: Copy Spring Boot JAR
      copy:
        src: target/EduSched-0.0.1-SNAPSHOT.jar 
        dest: /home/ec2-user/HTU-Schedemy-Website-Backend/target/EduSched-0.0.1-SNAPSHOT.jar
        owner: ec2-user
        mode: '0755'

    - name: Create Systemd Service File
      copy:
        dest: /etc/systemd/system/final.service
        content: |
          [Unit]
          Description=Schedemy Spring Boot Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/HTU-Schedemy-Website-Backend
          ExecStart=/usr/bin/java -jar /home/ec2-user/HTU-Schedemy-Website-Backend/target/EduSched-0.0.1-SNAPSHOT.jar
          SuccessExitStatus=143
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Enable the service
      systemd:
        name: final
        enabled: yes
